[FR-18420] change to block mode

diff --git a/.github/workflows/main-with-image.yaml b/.github/workflows/main-with-image.yaml
--- a/.github/workflows/main-with-image.yaml
+++ b/.github/workflows/main-with-image.yaml
@@ -344,6 +344,7 @@ jobs:
         if: ${{ steps.pre-deployment-validator.outputs.result == 'failure' }}
         run: |
           echo "Pre deployment validation failed. Please fix the issues and try again."
+          exit 1
       - name: Checkout Stress Tests
         uses: actions/checkout@v4
         with:
@@ -368,6 +369,7 @@ jobs:
         if: failure()
         run: |
           echo "Stress tests failed!"
+          exit 1
       - name: Checkout ${{ inputs.repository_name }}
         uses: actions/checkout@v4
         with:
@@ -455,6 +457,18 @@ jobs:
           echo deployments are not allowed at this time. Please contact the team
           echo "::error Deployments are not allowed at this time. It's probably Raz's fault"
           exit 1
+      - name: Pre Deployment Validation
+        id: pre-deployment-validator
+        uses: frontegg/pre-deploy-workflow-checks@master
+        with:
+          checkly-api-key: ${{ secrets.checkly_api_key }}
+          checkly-account-id: ${{ secrets.checkly_account_id }}
+          environment: ${{ inputs.au_environment_name }}
+      - name: Verify Pre Deployment Validation
+        if: ${{ steps.pre-deployment-validator.outputs.result == 'failure' }}
+        run: |
+          echo "Pre deployment validation failed. Please fix the issues and try again."
+          exit 1
       - name: Checkout ${{ inputs.repository_name }}
         uses: actions/checkout@v4
         with:
@@ -530,6 +544,18 @@ jobs:
         run: |
           echo deployments are not allowed at this time. Please contact the team
           echo "::error Deployments are not allowed at this time. It's probably Raz's fault"
+          exit 1
+      - name: Pre Deployment Validation
+        id: pre-deployment-validator
+        uses: frontegg/pre-deploy-workflow-checks@master
+        with:
+          checkly-api-key: ${{ secrets.checkly_api_key }}
+          checkly-account-id: ${{ secrets.checkly_account_id }}
+          environment: ${{ inputs.us_environment_name }}
+      - name: Verify Pre Deployment Validation
+        if: ${{ steps.pre-deployment-validator.outputs.result == 'failure' }}
+        run: |
+          echo "Pre deployment validation failed. Please fix the issues and try again."
           exit 1
       - name: Checkout ${{ inputs.repository_name }}
         uses: actions/checkout@v4
